services:
  postgres:
    image: postgres:16
    container_name: proposer_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=proposer
    volumes:
      - ./postgres:/var/lib/postgresql/data # persist the postgres data to disk so we don't lose it
    ports:
      - '5437:5432'
    networks:
      - shared_network

  proposer:
    build:
      context: ../.. #requires context from monorepo root for spvm-rs lib dependency
      dockerfile: ./apps/proposer/Dockerfile
    container_name: proposer
    env_file:
      - .env
    ports:
      - '7777:7777'
    depends_on:
      - postgres
    networks:
      - shared_network

networks:
  shared_network:
    external: true
