services:
  proposer:
    build:
      context: ../.. #requires context from monorepo root for spvm-rs lib dependency
      dockerfile: ./apps/proposer/Dockerfile
    container_name: proposer
    env_file:
      - ./.env
    ports:
      - '7777:7777'
    networks:
      - shared_network

networks:
  shared_network:
    external: true
