[workspace]
members = [
    "apps/enforcer",
    "apps/gateway-api",
    "apps/proposer-poc",
    "packages/spvm-rs",
    ]
resolver = "2"

#[workspace.dependencies]
#spvm-rs = { path = "packages/spvm-rs" }
