[workspace]
members = [
    "packages/spvm-rs",
    "apps/enforcer",
    "apps/gateway-api",
    "apps/proposer",
    "contracts",
    ]
resolver = "2"

#[workspace.dependencies]
#spvm-rs = { path = "packages/spvm-rs" }
