services:
  enforcer:
    build:
      context: ../.. #requires context from monorepo root for spvm-rs lib dependency
      dockerfile: ./apps/enforcer/Dockerfile
    container_name: enforcer
    env_file:
      - ./.env
    ports:
      - "1235:5555"
    networks:
      - shared_network

networks:
  shared_network:
    external: true
