[package]
name = "spvm-entity"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
name = "entity"
path = "lib.rs"

[dependencies]
serde = { version = "1", features = ["derive"] }

[dependencies.sea-orm]
version = "0.12.5" # sea-orm version