name: Spire PoC Monorepo
run-name: ${{ github.actor }} is gmi 🚀
on:
  workflow_dispatch: 
  
  push:
    branches: 
      - dev
      
  pull_request:
    branches: 
      - main

env:
  CARGO_TERM_COLOR: always
  FOUNDRY_PROFILE: ci

jobs:
  cargo-build:
    runs-on: ubuntu-latest
    steps:
      uses: actions/checkout@v4
      name: Build all apps
      run: cargo build -v

  forge-build:
      runs-on: ubuntu-latest
      name: Build and test smart contracts
      steps:
        uses: actions/checkout@v4
        with:
          submodules: recursive

        name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

        name: Run Forge build
        run: |
          cd packages/spvm-1
          forge --version
          forge build --sizes
        id: build

        name: Run Forge tests
        run: |
          cd packages/spvm-1
          forge test -vvv
        id: test

  docker-build:
    name: Build docker images
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@v4
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    -
      name: Login to DockerHub
      uses: docker/login-action@v3
      with: 
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Build and push
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: $/poc-monorepo:latest
