name: Spire PoC Monorepo
run-name: ${{ github.actor }} is gmi 🚀
on:
  workflow_dispatch: 
  
  push:
    branches: 
      - dev
      
  pull_request:
    branches: 
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build Gateway API
      run: cargo build -v --package gateway-api 
    - name: Build Enforcer
      run: cargo build -v --package enforcer
    - name: Build Proposer
      run: cargo build -v --package proposer-poc
