name: Spire PoC Monorepo
run-name: ${{ github.actor }} is gmi 🚀
on:
  workflow_dispatch: 
  
  push:
    branches: 
      - dev
      - main
      
  pull_request:
    branches: 
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build all apps
      run: cargo build -v
